[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "esr-analysis"
version = "0.1.0"
description = "Pipeline de análisis y procesamiento ESR"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "openpyxl",
    "PyPDF2",
    "cryptography",
    "huggingface-hub",
    "nltk",
    "sentence-transformers",
    "transformers",
    "torch",
    "bitsandbytes",
    "accelerate"
]

[project.scripts]
esr-pipeline = "esr_analysis.esr_pipeline:main"

[tool.setuptools.packages.find]
where = ["src"]
